name: minnie
channels:
  - omnia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - argcomplete=1.11.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - cython=0.29.14
  - decorator=4.4.1
  - dill=0.3.1.1
  - fftw3f=3.3.4
  - freetype=2.10.1
  - intel-openmp=2019.4
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - multiprocess=0.70.9
  - ncurses=6.1
  - networkx=2.4
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openmm=7.4.1
  - openssl=1.1.1g
  - pandas=0.25.1
  - pathos=0.2.5
  - patsy=0.5.1
  - pdbfixer=1.6
  - pip=19.3.1
  - pox=0.2.7
  - ppft=1.6.6.1
  - pyparsing=2.4.7
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - readline=7.0
  - scipy=1.4.1
  - seaborn=0.10.0
  - setuptools=44.0.0
  - six=1.13.0
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - tk=8.6.8
  - tornado=6.0.4
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
