name: minnie
channels:
  - omnia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  # Base dependencies
  - python
  - pip

  # Runtime dependencies
  - matplotlib
  - networkx
  - numpy
  - openmm
  - pandas
  - pathos
  - pdbfixer
  - seaborn

  # Developer dependencies
  - pip:
    - pre-commit
